# Generated by Django 4.2.29 on 2026-03-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="文章标题")),
                ("author", models.CharField(max_length=50, verbose_name="作者")),
                ("content", models.TextField(verbose_name="正文内容")),
                (
                    "publish_data",
                    models.DateTimeField(auto_now_add=True, verbose_name="发布时间"),
                ),
                ("views", models.IntegerField(default=0, verbose_name="阅读量")),
            ],
            options={
                "verbose_name": "科技文章",
                "verbose_name_plural": "科技文章",
            },
        ),
    ]
