# Generated by Django 4.2.29 on 2026-03-19 06:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="publish_data",
            new_name="publish_date",
        ),
    ]
